name: Django CI

on:
  push:
    branches: [ main , staging, dev, feature/**]
  pull_request:
    branches: [ main, staging, dev, feature/** ]


    
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tsuyoshicho/action-mypy@v3
        with:
          target: ddsc_web
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SOCIAL_AUTH_GITHUB_KEY: ${{ secrets.SOCIAL_AUTH_GITHUB_KEY }}
      SOCIAL_AUTH_GITHUB_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt
    - name: Run Unittest
      working-directory: ./ddsc_web
      run: |
        python manage.py test --settings=ddsc_web.settings.dev
    - name: Run System Checks
      working-directory: ./ddsc_web
      run: |
        python manage.py check --settings=ddsc_web.settings.dev
    - name: Code complexity check
      run: |
        xenon ddsc_web --max-absolute A --max-modules A --max-average A